/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenRouteImport } from './routes/women'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MenRouteImport } from './routes/men'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WomenTshirtRouteImport } from './routes/women.tshirt'
import { Route as WomenOversizedTshirtRouteImport } from './routes/women.oversized-tshirt'
import { Route as WomenHoodiesRouteImport } from './routes/women.hoodies'
import { Route as WomenCustomPrintedTshirtRouteImport } from './routes/women.custom-printed-tshirt'
import { Route as WomenCropTopRouteImport } from './routes/women.crop-top'
import { Route as WomenBomberJacketRouteImport } from './routes/women.bomber-jacket'
import { Route as WomenBodyconDressRouteImport } from './routes/women.bodycon-dress'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as MenTshirtRouteImport } from './routes/men.tshirt'
import { Route as MenSweatshirtRouteImport } from './routes/men.sweatshirt'
import { Route as MenOversizedTshirtRouteImport } from './routes/men.oversized-tshirt'
import { Route as MenHoodiesRouteImport } from './routes/men.hoodies'
import { Route as MenCustomPrintedTshirtRouteImport } from './routes/men.custom-printed-tshirt'
import { Route as AccessoriesPosterRouteImport } from './routes/accessories.poster'
import { Route as MenHoodiesZipRouteImport } from './routes/men.hoodies.zip'
import { Route as MenHoodiesPulloverRouteImport } from './routes/men.hoodies.pullover'
import { Route as MenHoodiesBomberRouteImport } from './routes/men.hoodies.bomber'
import { Route as MenHoodiesAcidWashRouteImport } from './routes/men.hoodies.acid-wash'
import { Route as AccessoriesPosterFramedRouteImport } from './routes/accessories.poster.framed'
import { Route as AccessoriesPosterCustomRouteImport } from './routes/accessories.poster.custom'
import { Route as AccessoriesPosterAcrylicRouteImport } from './routes/accessories.poster.acrylic'

const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenTshirtRoute = WomenTshirtRouteImport.update({
  id: '/tshirt',
  path: '/tshirt',
  getParentRoute: () => WomenRoute,
} as any)
const WomenOversizedTshirtRoute = WomenOversizedTshirtRouteImport.update({
  id: '/oversized-tshirt',
  path: '/oversized-tshirt',
  getParentRoute: () => WomenRoute,
} as any)
const WomenHoodiesRoute = WomenHoodiesRouteImport.update({
  id: '/hoodies',
  path: '/hoodies',
  getParentRoute: () => WomenRoute,
} as any)
const WomenCustomPrintedTshirtRoute =
  WomenCustomPrintedTshirtRouteImport.update({
    id: '/custom-printed-tshirt',
    path: '/custom-printed-tshirt',
    getParentRoute: () => WomenRoute,
  } as any)
const WomenCropTopRoute = WomenCropTopRouteImport.update({
  id: '/crop-top',
  path: '/crop-top',
  getParentRoute: () => WomenRoute,
} as any)
const WomenBomberJacketRoute = WomenBomberJacketRouteImport.update({
  id: '/bomber-jacket',
  path: '/bomber-jacket',
  getParentRoute: () => WomenRoute,
} as any)
const WomenBodyconDressRoute = WomenBodyconDressRouteImport.update({
  id: '/bodycon-dress',
  path: '/bodycon-dress',
  getParentRoute: () => WomenRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const MenTshirtRoute = MenTshirtRouteImport.update({
  id: '/tshirt',
  path: '/tshirt',
  getParentRoute: () => MenRoute,
} as any)
const MenSweatshirtRoute = MenSweatshirtRouteImport.update({
  id: '/sweatshirt',
  path: '/sweatshirt',
  getParentRoute: () => MenRoute,
} as any)
const MenOversizedTshirtRoute = MenOversizedTshirtRouteImport.update({
  id: '/oversized-tshirt',
  path: '/oversized-tshirt',
  getParentRoute: () => MenRoute,
} as any)
const MenHoodiesRoute = MenHoodiesRouteImport.update({
  id: '/hoodies',
  path: '/hoodies',
  getParentRoute: () => MenRoute,
} as any)
const MenCustomPrintedTshirtRoute = MenCustomPrintedTshirtRouteImport.update({
  id: '/custom-printed-tshirt',
  path: '/custom-printed-tshirt',
  getParentRoute: () => MenRoute,
} as any)
const AccessoriesPosterRoute = AccessoriesPosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => AccessoriesRoute,
} as any)
const MenHoodiesZipRoute = MenHoodiesZipRouteImport.update({
  id: '/zip',
  path: '/zip',
  getParentRoute: () => MenHoodiesRoute,
} as any)
const MenHoodiesPulloverRoute = MenHoodiesPulloverRouteImport.update({
  id: '/pullover',
  path: '/pullover',
  getParentRoute: () => MenHoodiesRoute,
} as any)
const MenHoodiesBomberRoute = MenHoodiesBomberRouteImport.update({
  id: '/bomber',
  path: '/bomber',
  getParentRoute: () => MenHoodiesRoute,
} as any)
const MenHoodiesAcidWashRoute = MenHoodiesAcidWashRouteImport.update({
  id: '/acid-wash',
  path: '/acid-wash',
  getParentRoute: () => MenHoodiesRoute,
} as any)
const AccessoriesPosterFramedRoute = AccessoriesPosterFramedRouteImport.update({
  id: '/framed',
  path: '/framed',
  getParentRoute: () => AccessoriesPosterRoute,
} as any)
const AccessoriesPosterCustomRoute = AccessoriesPosterCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => AccessoriesPosterRoute,
} as any)
const AccessoriesPosterAcrylicRoute =
  AccessoriesPosterAcrylicRouteImport.update({
    id: '/acrylic',
    path: '/acrylic',
    getParentRoute: () => AccessoriesPosterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/men': typeof MenRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/women': typeof WomenRouteWithChildren
  '/accessories/poster': typeof AccessoriesPosterRouteWithChildren
  '/men/custom-printed-tshirt': typeof MenCustomPrintedTshirtRoute
  '/men/hoodies': typeof MenHoodiesRouteWithChildren
  '/men/oversized-tshirt': typeof MenOversizedTshirtRoute
  '/men/sweatshirt': typeof MenSweatshirtRoute
  '/men/tshirt': typeof MenTshirtRoute
  '/product/$handle': typeof ProductHandleRoute
  '/women/bodycon-dress': typeof WomenBodyconDressRoute
  '/women/bomber-jacket': typeof WomenBomberJacketRoute
  '/women/crop-top': typeof WomenCropTopRoute
  '/women/custom-printed-tshirt': typeof WomenCustomPrintedTshirtRoute
  '/women/hoodies': typeof WomenHoodiesRoute
  '/women/oversized-tshirt': typeof WomenOversizedTshirtRoute
  '/women/tshirt': typeof WomenTshirtRoute
  '/accessories/poster/acrylic': typeof AccessoriesPosterAcrylicRoute
  '/accessories/poster/custom': typeof AccessoriesPosterCustomRoute
  '/accessories/poster/framed': typeof AccessoriesPosterFramedRoute
  '/men/hoodies/acid-wash': typeof MenHoodiesAcidWashRoute
  '/men/hoodies/bomber': typeof MenHoodiesBomberRoute
  '/men/hoodies/pullover': typeof MenHoodiesPulloverRoute
  '/men/hoodies/zip': typeof MenHoodiesZipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/men': typeof MenRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/women': typeof WomenRouteWithChildren
  '/accessories/poster': typeof AccessoriesPosterRouteWithChildren
  '/men/custom-printed-tshirt': typeof MenCustomPrintedTshirtRoute
  '/men/hoodies': typeof MenHoodiesRouteWithChildren
  '/men/oversized-tshirt': typeof MenOversizedTshirtRoute
  '/men/sweatshirt': typeof MenSweatshirtRoute
  '/men/tshirt': typeof MenTshirtRoute
  '/product/$handle': typeof ProductHandleRoute
  '/women/bodycon-dress': typeof WomenBodyconDressRoute
  '/women/bomber-jacket': typeof WomenBomberJacketRoute
  '/women/crop-top': typeof WomenCropTopRoute
  '/women/custom-printed-tshirt': typeof WomenCustomPrintedTshirtRoute
  '/women/hoodies': typeof WomenHoodiesRoute
  '/women/oversized-tshirt': typeof WomenOversizedTshirtRoute
  '/women/tshirt': typeof WomenTshirtRoute
  '/accessories/poster/acrylic': typeof AccessoriesPosterAcrylicRoute
  '/accessories/poster/custom': typeof AccessoriesPosterCustomRoute
  '/accessories/poster/framed': typeof AccessoriesPosterFramedRoute
  '/men/hoodies/acid-wash': typeof MenHoodiesAcidWashRoute
  '/men/hoodies/bomber': typeof MenHoodiesBomberRoute
  '/men/hoodies/pullover': typeof MenHoodiesPulloverRoute
  '/men/hoodies/zip': typeof MenHoodiesZipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/men': typeof MenRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/women': typeof WomenRouteWithChildren
  '/accessories/poster': typeof AccessoriesPosterRouteWithChildren
  '/men/custom-printed-tshirt': typeof MenCustomPrintedTshirtRoute
  '/men/hoodies': typeof MenHoodiesRouteWithChildren
  '/men/oversized-tshirt': typeof MenOversizedTshirtRoute
  '/men/sweatshirt': typeof MenSweatshirtRoute
  '/men/tshirt': typeof MenTshirtRoute
  '/product/$handle': typeof ProductHandleRoute
  '/women/bodycon-dress': typeof WomenBodyconDressRoute
  '/women/bomber-jacket': typeof WomenBomberJacketRoute
  '/women/crop-top': typeof WomenCropTopRoute
  '/women/custom-printed-tshirt': typeof WomenCustomPrintedTshirtRoute
  '/women/hoodies': typeof WomenHoodiesRoute
  '/women/oversized-tshirt': typeof WomenOversizedTshirtRoute
  '/women/tshirt': typeof WomenTshirtRoute
  '/accessories/poster/acrylic': typeof AccessoriesPosterAcrylicRoute
  '/accessories/poster/custom': typeof AccessoriesPosterCustomRoute
  '/accessories/poster/framed': typeof AccessoriesPosterFramedRoute
  '/men/hoodies/acid-wash': typeof MenHoodiesAcidWashRoute
  '/men/hoodies/bomber': typeof MenHoodiesBomberRoute
  '/men/hoodies/pullover': typeof MenHoodiesPulloverRoute
  '/men/hoodies/zip': typeof MenHoodiesZipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/collections'
    | '/contact'
    | '/faqs'
    | '/men'
    | '/our-story'
    | '/returns'
    | '/shipping'
    | '/women'
    | '/accessories/poster'
    | '/men/custom-printed-tshirt'
    | '/men/hoodies'
    | '/men/oversized-tshirt'
    | '/men/sweatshirt'
    | '/men/tshirt'
    | '/product/$handle'
    | '/women/bodycon-dress'
    | '/women/bomber-jacket'
    | '/women/crop-top'
    | '/women/custom-printed-tshirt'
    | '/women/hoodies'
    | '/women/oversized-tshirt'
    | '/women/tshirt'
    | '/accessories/poster/acrylic'
    | '/accessories/poster/custom'
    | '/accessories/poster/framed'
    | '/men/hoodies/acid-wash'
    | '/men/hoodies/bomber'
    | '/men/hoodies/pullover'
    | '/men/hoodies/zip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/collections'
    | '/contact'
    | '/faqs'
    | '/men'
    | '/our-story'
    | '/returns'
    | '/shipping'
    | '/women'
    | '/accessories/poster'
    | '/men/custom-printed-tshirt'
    | '/men/hoodies'
    | '/men/oversized-tshirt'
    | '/men/sweatshirt'
    | '/men/tshirt'
    | '/product/$handle'
    | '/women/bodycon-dress'
    | '/women/bomber-jacket'
    | '/women/crop-top'
    | '/women/custom-printed-tshirt'
    | '/women/hoodies'
    | '/women/oversized-tshirt'
    | '/women/tshirt'
    | '/accessories/poster/acrylic'
    | '/accessories/poster/custom'
    | '/accessories/poster/framed'
    | '/men/hoodies/acid-wash'
    | '/men/hoodies/bomber'
    | '/men/hoodies/pullover'
    | '/men/hoodies/zip'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/collections'
    | '/contact'
    | '/faqs'
    | '/men'
    | '/our-story'
    | '/returns'
    | '/shipping'
    | '/women'
    | '/accessories/poster'
    | '/men/custom-printed-tshirt'
    | '/men/hoodies'
    | '/men/oversized-tshirt'
    | '/men/sweatshirt'
    | '/men/tshirt'
    | '/product/$handle'
    | '/women/bodycon-dress'
    | '/women/bomber-jacket'
    | '/women/crop-top'
    | '/women/custom-printed-tshirt'
    | '/women/hoodies'
    | '/women/oversized-tshirt'
    | '/women/tshirt'
    | '/accessories/poster/acrylic'
    | '/accessories/poster/custom'
    | '/accessories/poster/framed'
    | '/men/hoodies/acid-wash'
    | '/men/hoodies/bomber'
    | '/men/hoodies/pullover'
    | '/men/hoodies/zip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRouteWithChildren
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  MenRoute: typeof MenRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  WomenRoute: typeof WomenRouteWithChildren
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women/tshirt': {
      id: '/women/tshirt'
      path: '/tshirt'
      fullPath: '/women/tshirt'
      preLoaderRoute: typeof WomenTshirtRouteImport
      parentRoute: typeof WomenRoute
    }
    '/women/oversized-tshirt': {
      id: '/women/oversized-tshirt'
      path: '/oversized-tshirt'
      fullPath: '/women/oversized-tshirt'
      preLoaderRoute: typeof WomenOversizedTshirtRouteImport
      parentRoute: typeof WomenRoute
    }
    '/women/hoodies': {
      id: '/women/hoodies'
      path: '/hoodies'
      fullPath: '/women/hoodies'
      preLoaderRoute: typeof WomenHoodiesRouteImport
      parentRoute: typeof WomenRoute
    }
    '/women/custom-printed-tshirt': {
      id: '/women/custom-printed-tshirt'
      path: '/custom-printed-tshirt'
      fullPath: '/women/custom-printed-tshirt'
      preLoaderRoute: typeof WomenCustomPrintedTshirtRouteImport
      parentRoute: typeof WomenRoute
    }
    '/women/crop-top': {
      id: '/women/crop-top'
      path: '/crop-top'
      fullPath: '/women/crop-top'
      preLoaderRoute: typeof WomenCropTopRouteImport
      parentRoute: typeof WomenRoute
    }
    '/women/bomber-jacket': {
      id: '/women/bomber-jacket'
      path: '/bomber-jacket'
      fullPath: '/women/bomber-jacket'
      preLoaderRoute: typeof WomenBomberJacketRouteImport
      parentRoute: typeof WomenRoute
    }
    '/women/bodycon-dress': {
      id: '/women/bodycon-dress'
      path: '/bodycon-dress'
      fullPath: '/women/bodycon-dress'
      preLoaderRoute: typeof WomenBodyconDressRouteImport
      parentRoute: typeof WomenRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men/tshirt': {
      id: '/men/tshirt'
      path: '/tshirt'
      fullPath: '/men/tshirt'
      preLoaderRoute: typeof MenTshirtRouteImport
      parentRoute: typeof MenRoute
    }
    '/men/sweatshirt': {
      id: '/men/sweatshirt'
      path: '/sweatshirt'
      fullPath: '/men/sweatshirt'
      preLoaderRoute: typeof MenSweatshirtRouteImport
      parentRoute: typeof MenRoute
    }
    '/men/oversized-tshirt': {
      id: '/men/oversized-tshirt'
      path: '/oversized-tshirt'
      fullPath: '/men/oversized-tshirt'
      preLoaderRoute: typeof MenOversizedTshirtRouteImport
      parentRoute: typeof MenRoute
    }
    '/men/hoodies': {
      id: '/men/hoodies'
      path: '/hoodies'
      fullPath: '/men/hoodies'
      preLoaderRoute: typeof MenHoodiesRouteImport
      parentRoute: typeof MenRoute
    }
    '/men/custom-printed-tshirt': {
      id: '/men/custom-printed-tshirt'
      path: '/custom-printed-tshirt'
      fullPath: '/men/custom-printed-tshirt'
      preLoaderRoute: typeof MenCustomPrintedTshirtRouteImport
      parentRoute: typeof MenRoute
    }
    '/accessories/poster': {
      id: '/accessories/poster'
      path: '/poster'
      fullPath: '/accessories/poster'
      preLoaderRoute: typeof AccessoriesPosterRouteImport
      parentRoute: typeof AccessoriesRoute
    }
    '/men/hoodies/zip': {
      id: '/men/hoodies/zip'
      path: '/zip'
      fullPath: '/men/hoodies/zip'
      preLoaderRoute: typeof MenHoodiesZipRouteImport
      parentRoute: typeof MenHoodiesRoute
    }
    '/men/hoodies/pullover': {
      id: '/men/hoodies/pullover'
      path: '/pullover'
      fullPath: '/men/hoodies/pullover'
      preLoaderRoute: typeof MenHoodiesPulloverRouteImport
      parentRoute: typeof MenHoodiesRoute
    }
    '/men/hoodies/bomber': {
      id: '/men/hoodies/bomber'
      path: '/bomber'
      fullPath: '/men/hoodies/bomber'
      preLoaderRoute: typeof MenHoodiesBomberRouteImport
      parentRoute: typeof MenHoodiesRoute
    }
    '/men/hoodies/acid-wash': {
      id: '/men/hoodies/acid-wash'
      path: '/acid-wash'
      fullPath: '/men/hoodies/acid-wash'
      preLoaderRoute: typeof MenHoodiesAcidWashRouteImport
      parentRoute: typeof MenHoodiesRoute
    }
    '/accessories/poster/framed': {
      id: '/accessories/poster/framed'
      path: '/framed'
      fullPath: '/accessories/poster/framed'
      preLoaderRoute: typeof AccessoriesPosterFramedRouteImport
      parentRoute: typeof AccessoriesPosterRoute
    }
    '/accessories/poster/custom': {
      id: '/accessories/poster/custom'
      path: '/custom'
      fullPath: '/accessories/poster/custom'
      preLoaderRoute: typeof AccessoriesPosterCustomRouteImport
      parentRoute: typeof AccessoriesPosterRoute
    }
    '/accessories/poster/acrylic': {
      id: '/accessories/poster/acrylic'
      path: '/acrylic'
      fullPath: '/accessories/poster/acrylic'
      preLoaderRoute: typeof AccessoriesPosterAcrylicRouteImport
      parentRoute: typeof AccessoriesPosterRoute
    }
  }
}

interface AccessoriesPosterRouteChildren {
  AccessoriesPosterAcrylicRoute: typeof AccessoriesPosterAcrylicRoute
  AccessoriesPosterCustomRoute: typeof AccessoriesPosterCustomRoute
  AccessoriesPosterFramedRoute: typeof AccessoriesPosterFramedRoute
}

const AccessoriesPosterRouteChildren: AccessoriesPosterRouteChildren = {
  AccessoriesPosterAcrylicRoute: AccessoriesPosterAcrylicRoute,
  AccessoriesPosterCustomRoute: AccessoriesPosterCustomRoute,
  AccessoriesPosterFramedRoute: AccessoriesPosterFramedRoute,
}

const AccessoriesPosterRouteWithChildren =
  AccessoriesPosterRoute._addFileChildren(AccessoriesPosterRouteChildren)

interface AccessoriesRouteChildren {
  AccessoriesPosterRoute: typeof AccessoriesPosterRouteWithChildren
}

const AccessoriesRouteChildren: AccessoriesRouteChildren = {
  AccessoriesPosterRoute: AccessoriesPosterRouteWithChildren,
}

const AccessoriesRouteWithChildren = AccessoriesRoute._addFileChildren(
  AccessoriesRouteChildren,
)

interface MenHoodiesRouteChildren {
  MenHoodiesAcidWashRoute: typeof MenHoodiesAcidWashRoute
  MenHoodiesBomberRoute: typeof MenHoodiesBomberRoute
  MenHoodiesPulloverRoute: typeof MenHoodiesPulloverRoute
  MenHoodiesZipRoute: typeof MenHoodiesZipRoute
}

const MenHoodiesRouteChildren: MenHoodiesRouteChildren = {
  MenHoodiesAcidWashRoute: MenHoodiesAcidWashRoute,
  MenHoodiesBomberRoute: MenHoodiesBomberRoute,
  MenHoodiesPulloverRoute: MenHoodiesPulloverRoute,
  MenHoodiesZipRoute: MenHoodiesZipRoute,
}

const MenHoodiesRouteWithChildren = MenHoodiesRoute._addFileChildren(
  MenHoodiesRouteChildren,
)

interface MenRouteChildren {
  MenCustomPrintedTshirtRoute: typeof MenCustomPrintedTshirtRoute
  MenHoodiesRoute: typeof MenHoodiesRouteWithChildren
  MenOversizedTshirtRoute: typeof MenOversizedTshirtRoute
  MenSweatshirtRoute: typeof MenSweatshirtRoute
  MenTshirtRoute: typeof MenTshirtRoute
}

const MenRouteChildren: MenRouteChildren = {
  MenCustomPrintedTshirtRoute: MenCustomPrintedTshirtRoute,
  MenHoodiesRoute: MenHoodiesRouteWithChildren,
  MenOversizedTshirtRoute: MenOversizedTshirtRoute,
  MenSweatshirtRoute: MenSweatshirtRoute,
  MenTshirtRoute: MenTshirtRoute,
}

const MenRouteWithChildren = MenRoute._addFileChildren(MenRouteChildren)

interface WomenRouteChildren {
  WomenBodyconDressRoute: typeof WomenBodyconDressRoute
  WomenBomberJacketRoute: typeof WomenBomberJacketRoute
  WomenCropTopRoute: typeof WomenCropTopRoute
  WomenCustomPrintedTshirtRoute: typeof WomenCustomPrintedTshirtRoute
  WomenHoodiesRoute: typeof WomenHoodiesRoute
  WomenOversizedTshirtRoute: typeof WomenOversizedTshirtRoute
  WomenTshirtRoute: typeof WomenTshirtRoute
}

const WomenRouteChildren: WomenRouteChildren = {
  WomenBodyconDressRoute: WomenBodyconDressRoute,
  WomenBomberJacketRoute: WomenBomberJacketRoute,
  WomenCropTopRoute: WomenCropTopRoute,
  WomenCustomPrintedTshirtRoute: WomenCustomPrintedTshirtRoute,
  WomenHoodiesRoute: WomenHoodiesRoute,
  WomenOversizedTshirtRoute: WomenOversizedTshirtRoute,
  WomenTshirtRoute: WomenTshirtRoute,
}

const WomenRouteWithChildren = WomenRoute._addFileChildren(WomenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRouteWithChildren,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  MenRoute: MenRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  WomenRoute: WomenRouteWithChildren,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
